### ISSUE TITLE
Darktheme

### ISSUE THREAD

**Issue by vijib** [nitro-bio/sequence-viewers#73] opened 2024-12-09 23:37 UTC
Any way possible to use dark theme instead of light theme default?

**Comment by ninjha01** [comment] 2024-12-10 20:07
Definitely, will add this to the docs tonight

**Comment by ninjha01** [comment] 2024-12-10 23:30
@vijib I [added some documetation](https://docs.nitro.bio/quickstart#dark-mode) describing how to use a dark theme. Basically you add the `dark` className to a parent element.

You can see the dark/light themes for the sequence viewer [here](https://docs.nitro.bio/SequenceViewer).

![CleanShot 2024-12-10 at 15 28 50@2x](https://github.com/user-attachments/assets/bb85d96b-617d-47c8-a7a4-0af78ebefca4)

Let me know if you run into any issues!

**Comment by ninjha01** [comment] 2024-12-12 02:17
Closing for now, happy to re-open

**Comment by vijib** [comment] 2024-12-13 19:10
<body class="dark">
  
</body> 
is not standard or reliable. class is not standard. Do you mean className. PLease provide exact documentation. Also the documentation for inclding in tailwindconfifg.css is also not working

**Comment by ninjha01** [comment] 2024-12-13 19:29
Good catch, I will update the documentation to use className. 

Can you share your tailwind config?

**Comment by vijib** [comment] 2024-12-13 23:46
// tailwind.config.js
export default {
  content: [
   ...,
   "./node_modules/@nitro-bio/sequence-viewers/dist/**/*.{js,ts,jsx,tsx}",
  ],
};

does it work ? Its not including css for me? Could you show the config that will work ? Also could you share the dark theme css too ?

**Comment by vijib** [comment] 2024-12-14 15:50
Adding className="dark" does nothing whatsoever to fix the issue where in a dark theme, we see white UI text on a white UI background. Could you provide an actual working case where dark theme will work. Also provide the real correct tailwind.config.js If your package will not work in this condition, just let me know. This is preferrable over providing something that does not work.

**Comment by ninjha01** [comment] 2024-12-14 18:05
Sorry about that - I've put together an [example repo](https://github.com/nitro-bio/example_nitro_ui/). [Here's](https://github.com/nitro-bio/example_nitro_ui/blob/main/src/App.tsx) an example of how the css import would work. And [here](https://github.com/nitro-bio/example_nitro_ui/blob/main/tailwind.config.js) is a working tailwind config.

---

I found some issues in [my documentation](https://docs.nitro.bio/SequenceViewer), which I have now fixed.

First, I put the wrong path for the css file. It should be `import "path/to/node_modules/@nitro-bio/sequence-viewers/dist/nitro.css";`

Secondly, I didn't document the need to define a `brand` and `noir` color if using the tailwind config.

```
const colors = require("tailwindcss/colors");
export default {
  darkMode: "class",
  content: [
	...
    "./node_modules/@nitro-bio/sequence-viewers/dist/nitro-ui.umd.js",
  ],
  theme: {
	...
    extend: {
	  ...
      colors: {
	    ...
        brand: colors.emerald,
        noir: colors.zinc,
      },
    },
  },
  plugins: [],
};
```

I've [updated the docs](https://docs.nitro.bio/SequenceViewer) to fix these issues.

**Comment by vijib** [comment] 2024-12-14 21:19
Thank you. I have tried and now I see the following issue. The Pos <number> is black text on black background rendering it invisible. the style is as follows
class="text-xs text-black dark:text-white"
how to tweak it to become white text ?

**Comment by ninjha01** [comment] 2024-12-14 22:21
So the path you've posted is the "real" path to the css/js files, while the one in the docs is a symlink to that path. I'm not entirely sure why neither work for you.

In any case, I've just published a new version of the library `1.0.4` that sets up styles to be imported via `import '@nitro-bio/sequence-viewers/dist/nitro.css';` Can you 

1) delete `node_modules`
2) run `pnpm add @nitro-bio/sequence-viewers@latest`
3) run `pnpm install`
4) Add `import '@nitro-bio/sequence-viewers/dist/nitro.css';` to your App.tsx

and let me know if that works?

**Comment by vijib** [comment] 2024-12-15 00:53
There are issues in this version too. The dark mode edit text areas show as white background with white text. The dark mode is not working with this case. What should the tailwindcss be in this case ?

**Comment by ninjha01** [comment] 2024-12-15 01:13
I’m sorry, not sure what the cause could be - can you share a repo reproducing the issue?On Dec 14, 2024, at 4:54 PM, vijib ***@***.***> wrote:﻿
There are issues in this version too. The dark mode edit text areas show as white background with white text. The dark mode is not working with this case. What should the tailwindcss be in this case ?

**Comment by vijib** [comment] 2024-12-15 02:46
Before your latest update the tailwindconfig css did not have the white text with white background in dark mode. After the latest change it does, please send me the new tailwind.config.js for this new version above.

**Comment by ninjha01** [comment] 2024-12-16 16:04
I don't see that background - could you share a screenshot?
![CleanShot 2024-12-16 at 08 00 52@2x](https://github.com/user-attachments/assets/aa313bfa-c34f-4e40-becc-d731a3208130)

**Comment by vijib** [comment] 2024-12-17 02:32
You'll see a problem if you a have input in the dark theme.
![Screenshot 2024-12-16 at 6 25 27 PM](https://github.com/user-attachments/assets/92e868c5-bae1-43e7-b2e3-c5efcbe764db)

Cause of the problem is the background-color: #fff 
If I remove this style I see


![Screenshot 2024-12-16 at 6 28 18 PM](https://github.com/user-attachments/assets/c14f7c2c-9e7b-45c6-bf27-545d0bbb46ad)

So we need a way to remove this background-color: #fff in dark theme. We should not see white text in white background of input making the input text area text invisible and there is an odd white background that is really harsh in the text area of black theme. This is one issue. There is another minor issue where Pos text is black on black ground making it invisible in dark theme. But the first issue of white text area in the dark theme is probably the worse issue.

**Comment by ninjha01** [comment] 2024-12-17 17:31
Ah okay I think I have a guess as to how to fix this. I should have something for you to try in a couple hours

**Comment by ninjha01** [comment] 2024-12-18 16:44
@vijib sorry, I thought I had understood your comment, but I realize now I don't.

Specifically, I don't understand why you're asking about these input components:

<img width="90" alt="image" src="https://github.com/user-attachments/assets/db49c91c-9ba6-4770-b941-5a82ccb36070" />

<img width="64" alt="image" src="https://github.com/user-attachments/assets/bfc70212-4765-4665-bb65-0554c7aaa240" />

These aren't provided by the `@nitro-bio/sequence-viewers` package and without a repo reproducing the error it's hard for me to figure out how to fix the dark mode styling on them.


For the `Pos` issue i've just pushed a new version of the package that should remove the `bg-inherit` class from them, hopefully this resolves the text color issue

**Comment by vijib** [comment] 2024-12-18 20:23
The nitro.css output by this library has two background: #fff under select, textarea as in the screenshot above
![Screenshot 2024-12-18 at 12 23 05 PM](https://github.com/user-attachments/assets/9baa7806-f5f5-463d-96e1-853d9363fcbe)
Could you remove this background-color:#fff in your css when using dark theme?

**Comment by vijib** [comment] 2024-12-18 20:51
@ninjha01  please help me out and all i request is remove the background-color:#fff in the nitro.css you provide if its dark theme. Could you do that please? Thanks

**Comment by ninjha01** [comment] 2024-12-18 20:52
I think I understand the problem now, let me look into a couple solutions

**Comment by ninjha01** [comment] 2024-12-18 21:10
I've just published version `1.0.6` which should no longer come with the input style override. 


Sorry for the long back and forth - It was hard to figure out where that css was coming from. Turns out I was unneccesarily using the @tailwindcss/forms library which includes a css reset for input elements. I have removed that library and so it should no longer override your styles.

**Comment by vijib** [comment] 2024-12-18 21:18
pnpm add @nitro-bio+sequence-viewers@1.0.6
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @nitro-bio+sequence-viewers@1.0.6 isn't supported by any available resolver

**Comment by ninjha01** [comment] 2024-12-18 21:33
ah true, it's in the dependencies but shouldn't be in the generated css.

I've made those changes available in `1.0.7`. Can you see if that works?

`pnpm add @nitro-bio/sequence-viewers@1.0.7`

**Comment by vijib** [comment] 2024-12-18 21:38
I dont think 1.0.7 is successfully published. Could you try it on your side?

**Comment by ninjha01** [comment] 2024-12-18 21:45
![Uploading CleanShot 2024-12-18 at 13.45.40@2x.png…]()

**Comment by vijib** [comment] 2024-12-18 21:47
The latest release of @nitro-bio/sequence-viewers is "1.0.5".

**Comment by ninjha01** [comment] 2024-12-18 21:47
Seems like the npm repository has the latest version https://www.npmjs.com/package/@nitro-bio/sequence-viewers?activeTab=versions ?

**Comment by vijib** [comment] 2024-12-18 21:49
@ninjha01 
I am unable to get anything past 1.0.5.

**Comment by vijib** [comment] 2024-12-18 21:52
could another contributor like @rmcl  or @digithed  help you out as well? Thanks

**Comment by ninjha01** [comment] 2024-12-18 22:02
I've been able to install version `1.0.7` on a couple different machines - could you clear your pnpm cache and retry?

**Comment by vijib** [comment] 2024-12-18 22:05
Same issue. 

pnpm clear cache -f
pnpm view @nitro-bio/sequence-viewers versions
(node:50341) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[ '1.0.0', '1.0.1', '1.0.2', '1.0.3', '1.0.4', '1.0.5' ]

**Comment by vijib** [comment] 2024-12-18 22:48
Thank you @ninjha01  I am able to download now. Though it took a while for me to get it. Apologies for the trouble earlier. The Pos:0 is still not visible. I am really sorry for the back and forth.

**Comment by vijib** [comment] 2024-12-18 22:58
![Screenshot 2024-12-16 at 6 44 48 PM](https://github.com/user-attachments/assets/ffde7538-1af6-4902-abd7-f10c6b95f5b7)
The cause of the invisible Pos: in dark theme is because text-black on black theme will render text invisible. 

when text-black is changed to text-white. The Pos:0 when text is black on dark theme makes it invisible.

Hope this clarifies

**Comment by vijib** [comment] 2024-12-19 03:15
dear @ninjha01  please help me out. Apologies for back and forth. Hope we can solve the Pos: issue where it shows up as black text against black background

**Comment by ninjha01** [comment] 2024-12-19 03:38
No worries, can you share a screenshot of the sequence viewer with the Pos not showing? As well as the html and styles?

**Comment by vijib** [comment] 2024-12-19 05:35
![Screenshot 2024-12-18 at 9 32 26 PM](https://github.com/user-attachments/assets/7ce5af97-c2c5-4593-a8f7-164596c5aeda)
HTML
![Screenshot 2024-12-18 at 9 33 36 PM](https://github.com/user-attachments/assets/40cc89b9-194d-473c-b8cb-58c7ec60906a)

The cause of the invisible Pos: in dark theme is because text-black on black theme will render text invisible.

when text-black is changed to text-white. The Pos:0 when text is black on dark theme makes it invisible.

**Comment by ninjha01** [comment] 2024-12-19 05:38
And have you put the `dark` className on a parent of the component? 
As in `<div className="dark <remainder of className">`
Don't see that in the screenshot.

**Comment by vijib** [comment] 2024-12-19 05:43
@ninjha01  I had it before and i removed it after i saw the white text from forms. Put it back again. Also your fix for the removal of tailwind forms fixed my white textarea background issue. You rock @ninjha01  thank you!

**Comment by ninjha01** [comment] 2024-12-19 05:44
Thank you for working with me to find and fix these bugs! Excited to get your feedback in the future

**Closed by ninjha01** 2024-12-19 05:44 UTC
